#define ENEMY_SNAIL_PLAYER_HITSTUN 30
#define ENEMY_SNAIL_PLAYER_INVUL 100
#define ENEMY_SNAIL_HEALTH 2
#define ENEMY_SNAIL_DAMAGE 2
#define ENEMY_SNAIL_WIDTH 13
#define ENEMY_SNAIL_HEIGHT 15

#define ENEMY_OWL_PLAYER_HITSTUN 30
#define ENEMY_OWL_PLAYER_INVUL 100
#define ENEMY_OWL_HEALTH 1
#define ENEMY_OWL_DAMAGE 5
#define ENEMY_OWL_WIDTH 13
#define ENEMY_OWL_HEIGHT 15