;this file for FamiTone3 library generated by text2vol tool
;edited by Doug Fraker, 2016-7, to add volume column, all notes

nes_bible_demo_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env4
	.byte $00
	.byte $30 ;instrument $05
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env3,@env0,@env5
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c9,$cf,$cc,$cb,$c9,$c9,$c6,$c4,$00,$07
@env2:
	.byte $cf,$cf,$cc,$c9,$c6,$c3,$c1,$00,$06
@env3:
	.byte $cf,$ce,$cd,$cb,$c8,$c5,$c3,$c2,$c1,$c0,$00,$09
@env4:
	.byte $c2,$c2,$c0,$00,$00
@env5:
	.byte $ff,$02,$fe,$e9,$a8,$80,$00,$05


; New song
@song0ch0:
	.byte $fb,$09
@song0ch0loop:
@ref0:
	.byte $80,$15,$85,$19,$85,$14,$85,$17,$85,$12,$85,$15,$85,$11,$85,$14
	.byte $85
@ref1:
	.byte $15,$85,$19,$85,$14,$85,$17,$85,$12,$85,$15,$85,$10,$85,$14,$85
@ref2:
	.byte $15,$85,$19,$85,$14,$85,$17,$85,$12,$85,$15,$85,$11,$85,$14,$85
	.byte $ff,$10
	.word @ref1
	.byte $ff,$10
	.word @ref2
	.byte $ff,$10
	.word @ref1
@ref6:
	.byte $12,$85,$14,$81,$15,$81,$10,$8d,$0e,$85,$10,$81,$12,$81,$0d,$8d
@ref7:
	.byte $12,$85,$14,$81,$15,$81,$17,$8d,$1a,$81,$15,$81,$14,$81,$15,$81
	.byte $14,$81,$12,$89
	.byte $ff,$10
	.word @ref2
	.byte $ff,$10
	.word @ref1
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref10:
	.byte $bf
@ref11:
	.byte $bf
@ref12:
	.byte $84,$25,$81,$21,$81,$20,$81,$1f,$81,$23,$81,$00,$85,$00,$81,$21
	.byte $81,$1e,$81,$1a,$81,$00,$81,$1d,$81,$1b,$81,$19,$81,$20,$81
@ref13:
	.byte $1e,$89,$00,$81,$1c,$81,$23,$81,$1c,$81,$00,$81,$1a,$81,$19,$81
	.byte $1a,$81,$1e,$81,$1d,$81,$1a,$81,$19,$81,$00,$81
@ref14:
	.byte $25,$81,$21,$81,$20,$81,$1f,$81,$23,$81,$00,$85,$00,$81,$21,$81
	.byte $1e,$81,$1a,$81,$00,$81,$1d,$81,$1b,$81,$19,$81,$20,$81
	.byte $ff,$1c
	.word @ref13
@ref16:
	.byte $bf
@ref17:
	.byte $bf
@ref18:
	.byte $89,$80,$26,$25,$23,$10,$87,$21,$20,$1e,$1a,$87,$1e,$1c,$1e,$19
	.byte $87,$25,$25,$25
@ref19:
	.byte $12,$87,$1e,$21,$25,$10,$87,$23,$1f,$1c,$1a,$87,$26,$25,$23,$22
	.byte $23,$22,$1e,$25,$83,$00
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref20:
	.byte $88,$09,$82,$12,$89,$00,$88,$09,$82,$10,$89,$00,$88,$09,$82,$1a
	.byte $89,$00,$88,$09,$82,$19,$89,$00
	.byte $ff,$10
	.word @ref20
	.byte $ff,$10
	.word @ref20
	.byte $ff,$10
	.word @ref20
	.byte $ff,$10
	.word @ref20
	.byte $ff,$10
	.word @ref20
@ref26:
	.byte $12,$8b,$00,$10,$8b,$00,$1a,$8b,$00,$19,$8b,$00
	.byte $ff,$0c
	.word @ref26
	.byte $ff,$0c
	.word @ref26
	.byte $ff,$0c
	.word @ref26
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref30:
	.byte $86,$01,$85,$0f,$85,$01,$85,$0f,$85,$01,$85,$0f,$85,$01,$85,$0f
	.byte $85
@ref31:
	.byte $01,$85,$0f,$85,$01,$85,$0f,$85,$01,$85,$0f,$85,$01,$85,$0f,$85
	.byte $ff,$10
	.word @ref31
	.byte $ff,$10
	.word @ref31
	.byte $ff,$10
	.word @ref31
	.byte $ff,$10
	.word @ref31
@ref36:
	.byte $10,$81,$0f,$81,$10,$81,$0f,$81,$10,$81,$0f,$81,$10,$81,$0f,$81
	.byte $10,$81,$0f,$81,$10,$81,$0f,$81,$10,$81,$0f,$81,$10,$81,$0f,$81
@ref37:
	.byte $10,$81,$0f,$81,$10,$81,$0f,$81,$10,$81,$0f,$81,$10,$81,$0f,$81
	.byte $10,$81,$0f,$81,$03,$81,$01,$81,$02,$85,$02,$02,$02,$81
	.byte $ff,$20
	.word @ref36
	.byte $ff,$1e
	.word @ref37
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref40:
	.byte $bf
@ref41:
	.byte $bf
@ref42:
	.byte $bf
@ref43:
	.byte $bf
@ref44:
	.byte $bf
@ref45:
	.byte $bf
@ref46:
	.byte $bf
@ref47:
	.byte $bf
@ref48:
	.byte $bf
@ref49:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
