;this file for FamiTone2 library generated by text2data tool

nes_bible_demo_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env4
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env1,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c9,$cf,$cc,$cb,$c9,$c9,$c6,$c4,$c2,$c1,$c0,$00,$04
@env2:
	.byte $cf,$cf,$cc,$c9,$c6,$c3,$c1,$c0,$00,$07
@env3:
	.byte $ce,$cd,$cb,$ca,$c9,$c9,$c8,$c7,$c7,$c6,$c4,$c3,$c3,$c2,$c1,$00
	.byte $0e
@env4:
	.byte $c2,$c2,$c0,$00,$00


; New song
@song0ch0:
	.byte $fb,$09
@song0ch0loop:
@ref0:
	.byte $80,$24,$85,$2c,$85,$22,$85,$28,$85,$1e,$85,$24,$85,$1c,$85,$22
	.byte $85
@ref1:
	.byte $24,$85,$2c,$85,$22,$85,$28,$85,$1e,$85,$24,$85,$1a,$85,$22,$85
@ref2:
	.byte $24,$85,$2c,$85,$22,$85,$28,$85,$1e,$85,$24,$85,$1c,$85,$22,$85
	.byte $ff,$10
	.word @ref1
	.byte $ff,$10
	.word @ref2
	.byte $ff,$10
	.word @ref1
	.byte $ff,$10
	.word @ref2
	.byte $ff,$10
	.word @ref1
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref8:
	.byte $bf
@ref9:
	.byte $bf
@ref10:
	.byte $86,$45,$3d,$3b,$39,$41,$01,$41,$01,$3d,$37,$2f,$01,$35,$31,$2d
	.byte $3a,$81
@ref11:
	.byte $37,$37,$37,$01,$33,$41,$33,$01,$2f,$2d,$2f,$37,$35,$2f,$2d,$00
	.byte $81
@ref12:
	.byte $45,$3d,$3b,$39,$41,$01,$41,$01,$3d,$37,$2f,$01,$35,$31,$2d,$3a
	.byte $81
	.byte $ff,$11
	.word @ref11
	.byte $ff,$11
	.word @ref12
	.byte $ff,$11
	.word @ref11
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref16:
	.byte $82,$1e,$8b,$00,$1a,$8b,$00,$2e,$8b,$00,$2c,$8b,$00
@ref17:
	.byte $1e,$8b,$00,$1a,$8b,$00,$2e,$8b,$00,$2c,$8b,$00
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0c
	.word @ref17
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref24:
	.byte $84,$12,$8b,$0e,$12,$8d,$0e,$8b,$0e,$12,$85,$0e,$85
@ref25:
	.byte $12,$8b,$12,$0e,$89,$0f,$12,$8b,$12,$0e,$85,$0e,$85
@ref26:
	.byte $12,$8b,$0e,$12,$8d,$0e,$8b,$0e,$12,$85,$0e,$85
	.byte $ff,$0d
	.word @ref25
	.byte $ff,$0c
	.word @ref26
	.byte $ff,$0d
	.word @ref25
	.byte $ff,$0c
	.word @ref26
	.byte $ff,$0d
	.word @ref25
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
